# Generated by Django 3.2.13 on 2022-05-08 15:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
