# Generated by Django 3.2.13 on 2022-05-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.CharField(default='2022', max_length=200),
            preserve_default=False,
        ),
    ]
